pipeline:
  filters:
    - name: LoadCSVFilter
      params:
        file_path: data/raw/limited_dataset.csv

    - name: DataTypeConverterFilter
      params:
        dtype_mapping:
          FL_DATE:
            dtype: datetime

          DEP_DELAY:
            dtype: Int16

          ARR_DELAY:
            dtype: Int16

          AIR_TIME:
            dtype: timedelta
            unit: minutes

          DISTANCE:
            dtype: Int32

          DEP_TIME:
            dtype: timedelta
            unit: hours

          ARR_TIME:
            dtype: timedelta
            unit: hours

    - name: ValidationFilter
      params:
        rules:
          - type: required_columns
            columns: [FL_DATE, DEP_DELAY, STATUS, ARR_DELAY, AIR_TIME]
            severity: warning #error

          - type: column_types
            schema:
              FL_DATE: datetime
              DEP_DELAY: Int16
              ARR_DELAY: Int16
              AIR_TIME: timedelta
              DISTANCE: Int32
              DEP_TIME: timedelta
              ARR_TIME: timedelta
            severity: warning

          - type: allowed_values
            schema:
              STATUS: [FINALIZADO, CANCELADO]
            severity: error

          - type: value_range
            schema:
              DEP_DELAY:
                min: 0 # -2000
                max: 2000 # 1379
                min_inclusive: true
                max_inclusive: true

              ARR_DELAY:
                min: -60
                max: 600
              PERCENTAGE:
                min: 0
                max: 100
            severity: warning

        fail_on:
          error:
            strategy: post
          warning:
            strategy: threshold
            threshold: 0.4

        row_actions:
          error: separate   # drop | keep | separate
          warning: separate # drop | keep | separate

        invalid_rows_path: data/reports/invalid_rows
        report_path: data/reports/validation_report.json

    - name: DataQualityMetricsFilter

    - name: DeduplicateFilter

    - name: CleanDataFilter

    - name: FilterByDateRange
      params:
        start_date: "2006-01-01"
        end_date: "2009-01-01"
        field_date: FL_DATE

    - name: SaveCSVFilter
      params:
        output_path: data/processed/sales_2023.csv
